### ISSUE TITLE
MAX_ANGLE. The reasoning of.

### ISSUE THREAD

**Issue by olehkodak** [chinyue/sas-proxy#1]
Hello @chinyue, great job. Thanks. 
Could you explain the meaning of constraint MAX_ANGLE? 
Underlying backgrounding? Why exactly 0xF800? Where is it coming from?
I assume there is some connection with "that the first 2 bytes of SAS message is 0x800C after starting the car without moving steering wheel" (Minor four bits are flags). 
Ie the maximum positive angle is 0x800 (2048 degrees), respectively, the maximum negative angle is 0xF800 (-2048 degrees).
Total, absolute maximum angle (positive and negative, or lock to lock) is MAX_ANGLE = 0xF800. 
If it's right, then what about the data range between maximum positive angle 0x800 and 0xFFF (-1 degrees)? Should we bypass it without scaling too(as in case MAX_ANGLE and above values)?

And, why are you not bypassing without scaling the message 0x800C? 
I understand that this message is necessary for initialize VDC ("hey SAS - here"). 
Or angle value does not matter on init? There are enough flags.

Thanks.

**Comment by chinyue** [comment]
Hi @olehkodak 
The 0xF800 is actually the return value from get_angle() if the initial value 0x800C is passed to it.
If we see 0xF800 from get_angle then we simply forward the initial state, assuming that some components might expect that initial state from CANBUS.

**Comment by olehkodak** [comment]
> Hi @olehkodak

Hi @chinyue, thanks for the reply.

> The 0xF800 is actually the return value from get_angle() if the initial value 0x800C is passed to it.
> If we see 0xF800 from get_angle then we simply forward the initial state, assuming that some components might expect that initial state from CANBUS.

I see it, now. Perfectly.
.
Can you tell me if the sensor sends packets continuously(at a certain frequency) or only once per angle changes?
Did you somehow estimate how many packets per second should be proxied and enough for this Arduino?

**Comment by chinyue** [comment]
> Can you tell me if the sensor sends packets continuously(at a certain frequency) or only once per angle changes?
> Did you somehow estimate how many packets per second should be proxied and enough for this Arduino?

The sensor sends packets continuously. That means it sends the initial 0x800C repeatedly before the steering wheel is turned and after that it sends the angle data continuously.
I didn't do a precise calculation but it feels like the sensor sends out the angle message every 100ms and Arduino is capable to handle that rate.
